### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by adenot** [DNXLabs/one-cli#3]
As a maintainer, I'd like to:
* Create a config file in my project under .dnx/config.yml
* Define versions of the tools used (terraform, aws, etc)
* Commit file with my project so developers can use without previous knowledge of the environment

As a developer,
* I will clone the project repository
* run `one` commands
It should work without problems with versions of tools used

Example of .one/config.yml:
```yaml
tools:
  terraform: dnxsolutions/terraform:0.12.24-dnx1
  aws: dnxsolutions/aws:1.16.263-dnx2
```
