### ISSUE TITLE
Static Applications support

### ISSUE THREAD

**Issue by arthurbdiniz** [DNXLabs/one-cli#83]
### Describe the solution you'd like

Be able to deploy static applications.

```
one app deploy
```

Maybe we will need to add these params to `one.yaml`
```
app:
  type: "static"
  name: "static-appplication"
  src: "./build"
  s3_bucket_name: "bucket_on_aws"
  distribution_id: 
```
